import React from 'react';

const Currency = ({ currencyValue, onChange }) => {
  return (
    <select value={currencyValue} onChange={(e) => onChange(e.target.value)} >
      <option value="">-- Select Currency Type --</option>
      <option value="AFN">	ADB Unit of Account	</option>
      <option value="EUR">	Afghani	</option>
      <option value="ALL">	Algerian Dinar	</option>
      <option value="DZD">	Argentine Peso	</option>
      <option value="AOA">	Armenian Dram	</option>
      <option value="XCD">	Aruban Florin	</option>
      <option value="ARS">	Australian Dollar	</option>
      <option value="AMD">	Azerbaijan Manat	</option>
      <option value="AWG">	Bahamian Dollar	</option>
      <option value="AUD">	Bahraini Dinar	</option>
      <option value="AZN">	Baht	</option>
      <option value="BSD">	Balboa	</option>
      <option value="BHD">	Barbados Dollar	</option>
      <option value="BDT">	Belarusian Ruble	</option>
      <option value="BBD">	Belize Dollar	</option>
      <option value="BYN">	Bermudian Dollar	</option>
      <option value="BZD">	Boliviano	</option>
      <option value="XOF">	Bolívar Soberano	</option>
      <option value="BMD">	Brazilian Real	</option>
      <option value="INR">	Brunei Dollar	</option>
      <option value="BTN">	Bulgarian Lev	</option>
      <option value="BOB">	Burundi Franc	</option>
      <option value="BOV">	CFA Franc BCEAO	</option>
      <option value="BAM">	CFA Franc BEAC	</option>
      <option value="BWP">	CFP Franc	</option>
      <option value="NOK">	Cabo Verde Escudo	</option>
      <option value="BRL">	Canadian Dollar	</option>
      <option value="BND">	Cayman Islands Dollar	</option>
      <option value="BGN">	Chilean Peso	</option>
      <option value="BIF">	Colombian Peso	</option>
      <option value="CVE">	Comorian Franc	</option>
      <option value="KHR">	Congolese Franc	</option>
      <option value="XAF">	Convertible Mark	</option>
      <option value="CAD">	Cordoba Oro	</option>
      <option value="KYD">	Costa Rican Colon	</option>
      <option value="CLP">	Cuban Peso	</option>
      <option value="CLF">	Czech Koruna	</option>
      <option value="CNY">	Dalasi	</option>
      <option value="COP">	Danish Krone	</option>
      <option value="CDF">	Denar	</option>
      <option value="NZD">	Djibouti Franc	</option>
      <option value="CRC">	Dobra	</option>
      <option value="HRK">	Dominican Peso	</option>
      <option value="CUP">	Dong	</option>
      <option value="CUC">	East Caribbean Dollar	</option>
      <option value="CZK">	Egyptian Pound	</option>
      <option value="DKK">	El Salvador Colon	</option>
      <option value="DJF">	Ethiopian Birr	</option>
      <option value="XCD">	Euro	</option>
      <option value="DOP">	Falkland Islands Pound	</option>
      <option value="EGP">	Fiji Dollar	</option>
      <option value="SVC">	Forint	</option>
      <option value="ERN">	Ghana Cedi	</option>
      <option value="ETB">	Gibraltar Pound	</option>
      <option value="FKP">	Gourde	</option>
      <option value="DKK">	Guarani	</option>
      <option value="FJD">	Guinean Franc	</option>
      <option value="XPF">	Guyana Dollar	</option>
      <option value="GMD">	Hong Kong Dollar	</option>
      <option value="GEL">	Hryvnia	</option>
      <option value="GHS">	Iceland Krona	</option>
      <option value="GIP">	Indian Rupee	</option>
      <option value="DKK">	Iranian Rial	</option>
      <option value="GTQ">	Iraqi Dinar	</option>
      <option value="GBP">	Jamaican Dollar	</option>
      <option value="GNF">	Jordanian Dinar	</option>
      <option value="GYD">	Kenyan Shilling	</option>
      <option value="HTG">	Kina	</option>
      <option value="HNL">	Kuna	</option>
      <option value="HKD">	Kuwaiti Dinar	</option>
      <option value="HUF">	Kwanza	</option>
      <option value="ISK">	Kyat	</option>
      <option value="IDR">	Lao Kip	</option>
      <option value="XDR">	Lari	</option>
      <option value="IRR">	Lebanese Pound	</option>
      <option value="IQD">	Lek	</option>
      <option value="ILS">	Lempira	</option>
      <option value="JMD">	Leone	</option>
      <option value="JPY">	Liberian Dollar	</option>
      <option value="JOD">	Libyan Dinar	</option>
      <option value="KZT">	Lilangeni	</option>
      <option value="KES">	Loti	</option>
      <option value="KPW">	Malagasy Ariary	</option>
      <option value="KRW">	Malawi Kwacha	</option>
      <option value="KWD">	Malaysian Ringgit	</option>
      <option value="KGS">	Mauritius Rupee	</option>
      <option value="LAK">	Mexican Peso	</option>
      <option value="LBP">	Mexican Unidad de Inversion (UDI)	</option>
      <option value="LSL">	Moldovan Leu	</option>
      <option value="ZAR">	Moroccan Dirham	</option>
      <option value="LYD">	Mozambique Metical	</option>
      <option value="CHF">	Mvdol	</option>
      <option value="MOP">	Naira	</option>
      <option value="MKD">	Nakfa	</option>
      <option value="MGA">	Namibia Dollar	</option>
      <option value="MWK">	Nepalese Rupee	</option>
      <option value="MYR">	Netherlands Antillean Guilder	</option>
      <option value="MRU">	New Israeli Sheqel	</option>
      <option value="MUR">	New Taiwan Dollar	</option>
      <option value="XUA">	New Zealand Dollar	</option>
      <option value="MNT">	Ngultrum	</option>
      <option value="MAD">	North Korean Won	</option>
      <option value="MZN">	Norwegian Krone	</option>
      <option value="NAD">	Ouguiya	</option>
      <option value="ZAR">	Pakistan Rupee	</option>
      <option value="NPR">	Pataca	</option>
      <option value="NZD">	Pa’anga	</option>
      <option value="NIO">	Peso Convertible	</option>
      <option value="NGN">	Peso Uruguayo	</option>
      <option value="NZD">	Philippine Peso	</option>
      <option value="NOK">	Pound Sterling	</option>
      <option value="PKR">	Pula	</option>
      <option value="PAB">	Qatari Rial	</option>
      <option value="PGK">	Quetzal	</option>
      <option value="PYG">	Rand	</option>
      <option value="NZD">	Rial Omani	</option>
      <option value="PLN">	Riel	</option>
      <option value="QAR">	Romanian Leu	</option>
      <option value="RON">	Rufiyaa	</option>
      <option value="RUB">	Rupiah	</option>
      <option value="RWF">	Russian Ruble	</option>
      <option value="SHP">	Rwanda Franc	</option>
      <option value="WST">	SDR (Special Drawing Right)	</option>
      <option value="STN">	Saint Helena Pound	</option>
      <option value="SAR">	Saudi Riyal	</option>
      <option value="RSD">	Serbian Dinar	</option>
      <option value="SCR">	Seychelles Rupee	</option>
      <option value="SLL">	Singapore Dollar	</option>
      <option value="SGD">	Sol	</option>
      <option value="ANG">	Solomon Islands Dollar	</option>
      <option value="XSU">	Som	</option>
      <option value="SBD">	Somali Shilling	</option>
      <option value="SOS">	Somoni	</option>
      <option value="ZAR">	South Sudanese Pound	</option>
      <option value="SSP">	Sri Lanka Rupee	</option>
      <option value="LKR">	Sucre	</option>
      <option value="SDG">	Sudanese Pound	</option>
      <option value="SRD">	Surinam Dollar	</option>
      <option value="SZL">	Swedish Krona	</option>
      <option value="SEK">	Swiss Franc	</option>
      <option value="CHE">	Syrian Pound	</option>
      <option value="CHW">	Taka	</option>
      <option value="SYP">	Tala	</option>
      <option value="TWD">	Tanzanian Shilling	</option>
      <option value="TJS">	Tenge	</option>
      <option value="TZS">	Trinidad and Tobago Dollar	</option>
      <option value="THB">	Tugrik	</option>
      <option value="USD">	Tunisian Dinar	</option>
      <option value="TOP">	Turkish Lira	</option>
      <option value="TTD">	Turkmenistan New Manat	</option>
      <option value="TND">	UAE Dirham	</option>
      <option value="TRY">	US Dollar	</option>
      <option value="TMT">	Uganda Shilling	</option>
      <option value="UGX">	Unidad Previsional	</option>
      <option value="UAH">	Unidad de Fomento	</option>
      <option value="AED">	Unidad de Valor Real	</option>
      <option value="GBP">	Uruguay Peso en Unidades Indexadas (UI)	</option>
      <option value="UYU">	Uzbekistan Sum	</option>
      <option value="UYI">	Vatu	</option>
      <option value="UYW">	WIR Euro	</option>
      <option value="UZS">	WIR Franc	</option>
      <option value="VUV">	Won	</option>
      <option value="VES">	Yemeni Rial	</option>
      <option value="VND">	Yen	</option>
      <option value="MAD">	Yuan Renminbi	</option>
      <option value="YER">	Zambian Kwacha	</option>
      <option value="ZMW">	Zimbabwe Dollar	</option>
      <option value="ZWL">	Zloty	</option>
    </select>
  )
}
export default Currency;
